# Generated by Django 5.1.7 on 2025-03-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024, unique=True)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('contractor', models.CharField(default='Unknown', max_length=255)),
                ('project', models.CharField(default='Unknown', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'ordering': ['-scan_date'],
                'indexes': [models.Index(fields=['contractor'], name='scanner_sca_contrac_f15e68_idx'), models.Index(fields=['project'], name='scanner_sca_project_956639_idx'), models.Index(fields=['file_type'], name='scanner_sca_file_ty_a7eac4_idx')],
            },
        ),
    ]
